version: '3.4'

services:
  sierratakehome.api:
    image: ${DOCKER_REGISTRY-}sierratakehomeapi
    build:
      context: .
      dockerfile: SierraTakeHome.Api/Dockerfile
    depends_on:
      - sqlserver
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "SierraTakeHome123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
